# Site
name: "Harry's Tech News"
title: "Harry's Tech News"
description: "Stay updated with the latest and greatest in technology!"
logo: 'assets/images/logo.png'  # Update this if you have a custom logo
favicon: 'assets/images/logo.png'  # Update this if you have a favicon
baseurl: ""  # Keep empty if hosted at root on GitHub Pages (e.g., https://yourusername.github.io/)
google_analytics: ""  # Replace with your Google Analytics tracking ID if you have one
disqus: 'harrystechnews'  # Replace with your Disqus shortname for comments
mailchimp-list: ""  # Remove or update if you plan to use Mailchimp for newsletters
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  harry:
    name: Harry Graham
    display_name: Harry Graham
    avatar: 'assets/images/avatar.png'  # Replace with your avatar if available
    email: your-email@example.com  # Add your email here
    web: https://harrystechnews.com  # Replace with your domain
    twitter: https://twitter.com/yourhandle  # Replace with your Twitter handle
    description: "Tech enthusiast and blogger sharing insights on the latest innovations and trends in the tech world."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6  # Number of posts per page
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (if applicable)
adsense: "disabled"  # Change to "enabled" if you want to activate Adsense
adsense-data-ad-client: ""  # Replace with your Adsense client ID
adsense-data-ad-slot: ""  # Replace with your Adsense slot ID

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"  # Enable for faster page load

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
